version: "2"
services:
  adminer:
    image: adminer
    restart: always
    networks:
      webnet:
        aliases:
          - adminer
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      webnet:
        aliases:
          - mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  student.api:
    container_name: monorepo-student-api
    env_file:
      - .env
    depends_on:
      - db
    networks:
      webnet:
        aliases:
          - student.api
    build:
      context: .
      dockerfile: ./apps/student-api/Dockerfile
    ports:
      - "3000:3000"
      - "5870:5870"
    volumes:
      - .:/src:cached
  student.client:
    container_name: monorepo-student-client
    networks:
      webnet:
        aliases:
          - student.client
    build:
      context: .
      dockerfile: ./apps/student-client/Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - .:/src:cached

networks:
  webnet:
volumes:
  db_data:
